import random
import time


#Variablen:
antwort = ""
weiter1 = False
versuche = 1

#Aufgabenstellung
input("Guten Tag")

input("Die Frage lautet:")
input("Ein Rennfahrer soll zwei Runden fahren")
input("und dabei eine Duschschnitts-Geschwindigkeit von 60km/h erreichen. ")
input("Eine Runde hat eine Distanz von 1km.")
input("Leider schafft er bei der ersten Runde nur eine")
input("durchschnittliche Geschwindigkeit von 40km/h.")
input("Wie schnell muss er in der zweiten Runde fahren,")
input("um die 60km/h zu erreichen?")
time.sleep(0.5)
print("(Sie müssen keine Einheit angeben, die Einheit ist km/h.)")
print("")
print("")
print("")
#Programm
while weiter1 == False:
    time.sleep(0.5)
    antwort = input("Was ist deine Antwort? ")
    antwort = int(antwort)
    if antwort == 120:
        time.sleep(0.5)
        print("Du hast es Geschaft...")
        time.sleep(0.5)
        print("und dabei " + str(versuche) + " Versuche gebraucht.")
        time.sleep(0.5)
        print("Ende...")
        weiter1 = True
    else:
        time.sleep(0.5)
        print("Leider Falsch")
        versuche = versuche + 1




 #NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN
 # NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN
 #  NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN
 #   NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN
 #    NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN
  #    NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN NICHT SPICKEN
 #NICHT SPICKEN



























































